#!/usr/bin/env ruby
#require 'benchmark'
require 'optparse'
require 'date'
require 'pp'
require 'mongoid'
require 'amqp'
require 'mq'

#Rubinius::CodeLoader.require_compiled "#{File.dirname(__FILE__)}/lib/optparse_receiver"
#Rubinius::CodeLoader.require_compiled "#{File.dirname(__FILE__)}/lib/receiver_inbox"
#Rubinius::CodeLoader.require_compiled "#{File.dirname(__FILE__)}/lib/commander"
require "#{File.dirname(__FILE__)}/lib/optparse_receiver"
require "#{File.dirname(__FILE__)}/lib/receiver_inbox"
require "#{File.dirname(__FILE__)}/lib/commander"

# %P => receiver(us)# %p => sender # %a => message %t => datetime %d => delivery_report_value %c message coding %u billing_information %D metadata

ReceiverInbox.perform(ARGV)
